app:
  
  ##### Default path if not specified #####
  
  # For windows
  # wireguard_path: C:\Program Files\WireGuard\wireguard.exe
  # wstunnel_path: .\wstunnel.exe # download from https://github.com/erebe/wstunnel/releases
  
  # For linux
  #wireguard_path: wg-quick #find in $PATH
  #wstunnel_path: ./wstunnel # download from https://github.com/erebe/wstunnel/releases
  
  ##### Other settings #####

  start_wireguard: true
  start_wstunnel: true
  
  # Interval in secs to send a ping to wstunnel server. Restarts wstunnel if ping fails. set 0 to disable. 
  healthcheck_ping_interval: 0   # **Redundant** patched in wstunnel >v6.0

  # Number of tries to fetch public IP, set 0 to disable
  healthcheck_ip_tries: 3 


  export_wireguard_conf: false # export temp conf to current directory


wstunnel:
  # see https://github.com/erebe/wstunnel

  # Required
  - server: wss://www.example.com:443
  - local-to-remote: udp://0.0.0.0:51820:127.0.0.1:51820?timeout_sec=0 # if multiple local-to-remote is set, the first one will be used to set wireguard endpoint server

  # Optional
  #- http-upgrade-path-prefix: wstunnel
  #- http-upgrade-credentials: user:pass
  #- tls-sni-override: wss.server.example.com

wireguard:
  # For AllowedIPs in windows (app os==windows):
  # ::/0 is ignored and,
  # ::/1, 8000::/1' is automatically added 

  # Endpoint will be overwritten to wstunnel_listen_ip:wstunnel_listen_port

  # path to wireguard config. 'str' is ignored if set
  #path: ./test.conf
  
  # wireguard config string
  str: |
    [Interface]
    PrivateKey=
    Address=
    DNS=1.1.1.1, 8.8.8.8

    [Peer]
    PublicKey=
    PresharedKey=
    AllowedIPs = 0.0.0.0/0, ::/0
    PersistentKeepalive = 20
    Endpoint = 127.0.0.1:51820
