app:
  logging:
    file: output.log
    level: INFO

wstunnel: # see https://github.com/erebe/wstunnel
  path:
    windows: .\wstunnel.exe
    linux: ./wstunnel
    darwin: ./wstunnel

  args:
    # Required
    server: wss://www.example.com:443
    local-to-remote: udp://0.0.0.0:51820:127.0.0.1:51820?timeout_sec=0

    # Optional
    #http-upgrade-path-prefix: ...
    #http-upgrade-credentials: ...
    #tls-sni-override: wss.server.example.com

wireguard:
  path:
    windows: C:\Program Files\WireGuard\wireguard.exe
    linux: /usr/bin/wireguard
    darwin: /usr/local/bin/wireguard

  config:
    #path: ./test.conf
    str:
      | # Ignored if 'path' is set, AllowedIPs & Address will be replaced automatically
      [Interface]
      PrivateKey=
      Address=
      DNS=1.1.1.1, 8.8.8.8

      [Peer]
      PublicKey=
      PresharedKey=
      AllowedIPs = 0.0.0.0/0, ::/0
      PersistentKeepalive = 20
      Endpoint = 127.0.0.1:51820

healthcheck:
  ip: # Number of tries to fetch public IP at the start of connection (stops after 5 times)
    enabled: True
    interval: 15
    restart:
      wstunnel: False
      wireguard: False

  ping: # Send a ping to wstunnel server every n secs
    enabled: True
    interval: 30
    restart:
      wstunnel: True
      wireguard: False

  state: # monitors wstunnel process state and check if wireguard tunnels are installed
    enabled: True
    interval: 5
    restart:
      wstunnel: True
      wireguard: True
